# docker-compose.yaml
version: "3.8"

services:
  db:
    container_name: drinkwater_db
    env_file:
      - .env
    image: postgres:15.4-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    container_name: drinkwater_app
    env_file:
      - .env
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      NODE_ENV: development
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      # JWT_SECRET: ${JWT_SECRET}
    command: ["npx", "nodemon", "-L"]
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

volumes:
  postgres-data:
